blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
    url(r'^$', views.blog_index, name='blog_index'),
    url(r'^post/$', views.blog_index, name='blog_index'),
    url(r'^view-post/(?P<pk>[^\.]+)$', views.view_post, name='view_post'),
    url(r'^category/(?P<pk>[^\.]+)$', views.view_category, name='view_category'),
    url(r'^new-post/$', views.new_post, name='new_post'),
]

nyarai_web/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from portfolio.views import index

admin.site.site_header = 'Nyarai Tunjera Site Admin Panel'
urlpatterns = [
    url(r'^$', index, name='home'),
    url(r'^admin/', admin.site.urls),
    url("portfolio/", include("portfolio.urls", namespace="portfolio")),
    url("blog/", include("blog.urls", namespace="blog")),
]

portfolio/urls.py
from django.conf.urls import url

from portfolio import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^publications/$', views.publications, name='publications'),
    url(r'^achievements_rewards/$', views.achievements_rewards, name='achievements_rewards'),
    url(r'^community_service/$', views.community_service, name='community_service'),
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^contact/$', views.contact, name='contact'),
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _

CATEGORY_CHOICES = (
    ('Achievements and Rewards', _('Achievements and Rewards')),
    ('Community Service', _('Community Service')),
    ('Contact', _('Contact')),
    ('Gallery', _('Gallery')),
    ('Publications', _('Publications')),
)

# Create your models here.
class Category(models.Model):
     name = models.CharField(
        choices=CATEGORY_CHOICES,
        verbose_name=_('Category'),
        max_length=30,
        blank=True, null=True
    )

     def __unicode__(self):
       return '%s' % self.name
 
class Post(models.Model):
     title = models.CharField(max_length=255)
     body = models.TextField()
     created_on = models.DateTimeField(auto_now_add=True)
     last_modified = models.DateTimeField(auto_now=True)
     category = models.ForeignKey('blog.Category', null=True)


class Comment(models.Model):
     author = models.CharField(max_length=60)
     body = models.TextField()
     created_on = models.DateTimeField(auto_now_add=True)
     post = models.ForeignKey('Post', on_delete=models.CASCADE)

portfolio/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from blog.models import Post, Comment


class PostForm(forms.ModelForm):
    title = forms.CharField(widget=forms.Textarea(attrs={'cols': 60, 'rows': 5, "placeholder": "add tittle of your post here!"}))
    body = forms.CharField(widget=forms.Textarea(
        attrs={
            "class": "form-control",
            "placeholder": "add your post here!"
        })
    )
    class Meta:
        model = Post
        exclude = ['']

class CommentForm(forms.ModelForm):
    author = forms.CharField(
        max_length=60,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Type Your Name"
        })
    )
    body = forms.CharField(widget=forms.Textarea(
        attrs={
            "class": "form-control",
            "placeholder": "Leave a comment here!"
        })
    )

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Comment
        fields = [
            'author', 'body'
        ]

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render_to_response, get_object_or_404
from django.shortcuts import render, redirect
import requests
from blog.models import Post, Category, Comment
from .forms import CommentForm, PostForm
from django.contrib import messages
from django.template import RequestContext

 
def blog_index(request):
     posts = Post.objects.all().order_by('-created_on')
     context = {
         "posts": posts,
     }
     return render(request, "blog/blog_index.html", context)
    
def view_category(request, pk):
   category = get_object_or_404(Category, pk=pk)
   return render_to_response('blog/view_category.html', {
       'category': category,
       'posts': Post.objects.filter(category=category)[:5]
   })


def view_post(request, pk):
    post = Post.objects.get(pk=pk)
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                author=form.cleaned_data["author"],
                body=form.cleaned_data["body"],
                post=post
            )
            comment.save()
    comments = Comment.objects.filter(post=post)   
    return render(request, 'blog/comment_post.html', {
       'post': get_object_or_404(Post, pk=pk),
       'comments': comments,
       'form': form,
   })

def new_post(request):
    template = 'blog/new_post.html'
    form = PostForm(request.POST or None)

    try:
        if form.is_valid():
            form.save()
            messages.success(request, 'Your blog Post has been saved')
    except Exception as e:
        messages.warning(request, 'Your blog Post has not been saved to do an eror {}'.format(e))
    
    context = {
        'form': form,
    }
    return render(request, template, context)

portfolio/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.shortcuts import render_to_response, redirect, get_object_or_404
import requests
from django.conf import settings
from django.template import RequestContext
from django.http import HttpResponse


def index(request):
    return render(request,'portfolio/index.html', {})

def home(request):
    return render(request,'portfolio/home.html', {})

def publications(request):
    return render(request,'portfolio/publications.html', {})

def achievements_rewards(request):
    return render(request,'portfolio/achievements_rewards.html', {})

def community_service(request):
    return render(request,'portfolio/community_service.html', {})

def gallery(request):
    return render(request,'portfolio/gallery.html', {})

def contact(request):
    return render(request,'portfolio/contact.html', {})

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><center>Nyarai Tunjera Website</center></title>
    <!-- bootsrap link -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block extrahead %}
    {% endblock %}
</head>
{% block header %}
{% endblock %}
<body>
    <div class="topheader" data-role="header" data-theme="a" style="background-color:rgb(0, 247, 255)">
        <h1 class="icon" style="color:black; padding-top:70px"><center>@Nyarai Tunjera Website</center></h1>
    </div><!-- /header -->
    <div class="topnav" >
        <a href="{% url "portfolio:home" %}">Home</a>
        <a href="{% url "portfolio:publications" %}">Publications</a>
        <a href="{% url "portfolio:achievements_rewards" %}">Achievements and Awards</a>
        <div class="topnav-right">
            <a href="{% url "portfolio:community_service" %}">Community service</a>
            <a href="{% url "portfolio:gallery" %}">Gallery</a>
            <a href="{% url "portfolio:contact" %}">Contact</a>
        </div>
        <a href="" class="icon" onclick="responsiveFunction()">
            <i class="fa fa-bars"></i>
        </a>
    </div>
<div data-role="page" id="{% block page_id %}home{% endblock %}">
    <div data-role="header">
    {% block content %}{% endblock %}
    </div>
    <footer class="bg-dark footer-section">
        <div class="border-top text-center border-dark py-3" style="color: #ddd">
          <div data-role="footer" data-theme="a">
            <h5><center>&copy; {% now 'Y' %} Nyarai Tunjera (Pty) Ltd, all rights reserved</center></h5>
        </div><!-- /footer -->
        </div>
      </footer>
      <!-- /footer -->
</div>
<script>
        function responsiveFunction() {
          var x = document.getElementById("myTopnav");
          if (x.className === "topnav") {
            x.className += " responsive";
          } else {
            x.className = "topnav";
          }
        }
</script>
</body>
</html

blog/templates/blog/blog_index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="topnav" data-role="header" data-theme="a" style="background-color:rgb(29, 141, 141)">
    <h2 style="color:white"><center>View Blog Posts</center></h2>
</div><!-- /header -->
<div class="col-md-10 offset-md-1" style="background-color:azure">
    <br>
      <p><h1>Blog Posts</h1></p>
      <hr>
      {% if posts %}
      {% for post in posts %}
      <h2><a href="{% url 'blog:view_post' post.pk %}">{{ post.title | title }}</a></h2>
      <small>
          {{ post.created_on.date }} |&nbsp;
         Categories:&nbsp;
         {% for category in post.categories.all %}
         <a href="{% url 'blog:view_category' category.name %}">
             {{ category.name }}
         </a>&nbsp;
         {% endfor %}
     </small>
     <p>{{ post.body | slice:":400" }}...</p>
     {% endfor %}
     {% else %}
     <p>There no posts</p>
     {% endif %}
 </div>
 {% endblock %}

blog/templates/blog/comment_post.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="topnav" data-role="header" data-theme="a" style="background-color:rgb(29, 141, 141)">
    <h2 style="color:white"><center>Comment Nyarai Tunjera's Post</center></h2>
</div><!-- /header -->
  <div class="col-md-10 offset-md-1" style="background-color:azure">
    <br>
      <p><h1>{{ post.title | title }}</h1></p>
      <small>
          {{ post.created_on.date }} |&nbsp;
          Categories:&nbsp;
          {% for category in post.categories.all %}
          <a href="{% url 'blog:view_category' category.name %}">
             {{ category.name }}
         </a>&nbsp;
         {% endfor %}
     </small>
     <p>{{ post.body | linebreaks }}</p>
     <h3>Leave a comment:</h3>
     <form method="post" action={% url 'blog:view_post' post.pk %}>
         {% csrf_token %}
         <div class="form-group">
             {{ form.author }}
         </div>
         <div class="form-group">
             {{ form.body }}
         </div>
         <p><input type="submit" name="add" style="background-color:teal; width: 100px; height: 50px; font-size: 14; color: rgb(243, 246, 250)" value="Comment"/></p>
     </form>
     <br>
     <h3>Comments:</h3>
     <div>
        {% for comment in comments %}
            <p>
                On {{comment.created_on.date }}&nbsp;
                <b>{{ comment.author }}</b> wrote:
            </p>
            <p>{{ comment.body }}</p>
            <hr>
        {% endfor %}
    </div>
     <div>
        <p><button><a href="{% url "blog:blog_index" %}"">Click to view blog posts</a></button></p>
     </div>
 </div>
 {% endblock %}

blog/templates/blog/new_post.html
{% extends 'base.html' %} 
{% block content %}
<div class="topnav" data-role="header" data-theme="a" style="background-color:rgb(29, 141, 141)">
    <h2 style="color:white"><center>Add post for Nyarai Tunjera's blog</center></h2>
</div><!-- /header -->
<div class="col-md-10 offset-md-1" style="background-color:azure">
    <br>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <br>
        <input type="submit" name="add" style="background-color:teal; width: 100px; height: 50px; font-size: 14; color: rgb(243, 246, 250)" value="Add Post"/>
    </form>
    <h2>{{ post.title }}</h2>
    <div class="content">
        <p>
            {{ post.body }}
        </p>
    </div>
    <div>
        <p><button><a href="{% url "portfolio:home" %}" data-direction="reverse" class="ui-btn ui-shadow ui-corner-all ui-btn-b">Go to Home page</a></button></p>
    </div>
</div>
{% endblock %}

blog/templates/blog/view_category.html
{% extends 'base.html' %} 
{% block head_title %}Viewing category {{ category.title }}{% endblock %}
{% block title %}{{ category.title }}{% endblock %}
 
{% block content %}
<div class="col-md-10 offset-md-1" style="background-color:azure">
    <br>
   {% if posts %}
   <p><h1>{{ category | title }}</h1></p>
   <hr>
       <ul>
       {% for post in posts %}
           <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
           <h3>Leave a comment:</h3>
            <form action="/blog/{{ post.pk }}/" method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.author }}
                </div>
                <div class="form-group">
                    {{ form.body }}
                </div>
                <!--<button type="submit" class="btn btn-primary">Submit</button>-->
                <input type="submit" name="add" style="background-color:teal; width: 100px; height: 50px; font-size: 14; color: rgb(243, 246, 250)" value="Add Post"/>
            </form>
            <h3>Comments:</h3>
            {% for comment in comments %}
            <p>
                On {{comment.created_on.date }}&nbsp;
                <b>{{ comment.author }}</b> wrote:
            </p>
            <p>{{ comment.body }}</p>
            <hr>
            {% endfor %}
       {% endfor %}
       </ul>
   {% else %}
       <p>There are no posts.</p>
   {% endif %}
</div>
{% endblock %}

blog/templates/blog/view_post.html
{% extends 'base.html' %}
{% load static %} 
{% block head_title %}{{ post.title }}{% endblock %}
{% block title %}{{ post.title }}{% endblock %}
 
{% block content %}
<div class="topnav" data-role="header" data-theme="a" style="background-color:rgb(29, 141, 141)">
    <h2 style="color:white"><center>View Nyarai Tunjera's post</center></h2>
</div><!-- /header -->
<br>
<br>
<div class="col-md-10 offset-md-1" style="background-color:azure">
    <div>
        <div>
            <p><center><h3>{{ post.title }}</h3></center></p>
        </div>
    </div>
    <hr>
    <p><center>{{ post.body }}</center></p>
</div>
<p><a href="{% url "blog:comment_post" %}" data-direction="reverse" class="ui-btn ui-shadow ui-corner-all ui-btn-b">Comment Post</a></p>
<br>
<br>
{% endblock %}

nyarai_web/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><center>Nyarai Tunjera Website</center></title>
    <!-- bootsrap link -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block extrahead %}
    {% endblock %}
</head>
{% block header %}
{% endblock %}
<body>
    <div class="topheader" data-role="header" data-theme="a" style="background-color:rgb(0, 247, 255)">
        <h1 class="icon" style="color:black; padding-top:70px"><center>@Nyarai Tunjera Website</center></h1>
    </div><!-- /header -->
    <div class="topnav" >
        <a href="{% url "portfolio:home" %}">Home</a>
        <a href="{% url "portfolio:publications" %}">Publications</a>
        <a href="{% url "portfolio:achievements_rewards" %}">Achievements and Awards</a>
        <div class="topnav-right">
            <a href="{% url "portfolio:community_service" %}">Community service</a>
            <a href="{% url "portfolio:gallery" %}">Gallery</a>
            <a href="{% url "portfolio:contact" %}">Contact</a>
        </div>
        <a href="" class="icon" onclick="responsiveFunction()">
            <i class="fa fa-bars"></i>
        </a>
    </div>
<div data-role="page" id="{% block page_id %}home{% endblock %}">
    <div data-role="header">
    {% block content %}{% endblock %}
    </div>
    <footer class="bg-dark footer-section">
        <div class="border-top text-center border-dark py-3" style="color: #ddd">
          <div data-role="footer" data-theme="a">
            <h5><center>&copy; {% now 'Y' %} Nyarai Tunjera (Pty) Ltd, all rights reserved</center></h5>
        </div><!-- /footer -->
        </div>
      </footer>
      <!-- /footer -->
</div>
<script>
        function responsiveFunction() {
          var x = document.getElementById("myTopnav");
          if (x.className === "topnav") {
            x.className += " responsive";
          } else {
            x.className = "topnav";
          }
        }
</script>
</body>
</html

portfolio/templates/portfolio/achievements_rewards.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="col-md-10 offset-md-1" style="background-color:azure">
  <br>
  <p><h1>Achievements and Awards</h1></p>
  <hr>
  <br>
  <h4>Professional affiliations</h4>
  <ol>
     <li>Institute of Information Technology Professionals South Africa (IITPSA)</li>
     <li>Associate Member – Computer Society of Zimbabwe since 2003</li>
  </ol>
     <br>
   <h4>Funding / Scholarships</h4>
     <ol>
        <li>NRF scholarship (2019)</li>
        <li>Scholars at Risk funding (2014)</li>
        <li>Andrew Mellon Scholarship (2012-2014)</li>
        <li>BUSE Research Grant (2012):</li>
      </ol>
      <br>
   <h4><b>Certifications</b></h4>
  <ol>
    <li>Careers Services Certificated recipient (2014)</li>
    <li>International Computer Driving Licence (ICDL)</li>
  </ol>
</div>
 {% endblock %}

portfolio/templates/portfolio/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><center>Nyarai Tunjera Website</center></title>
    <!-- bootsrap link -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block extrahead %}
    {% endblock %}
</head>
{% block header %}
{% endblock %}
<body>
    <div class="topheader" data-role="header" data-theme="a" style="background-color:rgb(0, 247, 255)">
        <h1 class="icon" style="color:black; padding-top:70px"><center>@Nyarai Tunjera Website</center></h1>
    </div><!-- /header -->
    <div class="topnav" >
        <a href="{% url "portfolio:home" %}">Home</a>
        <a href="{% url "portfolio:publications" %}">Publications</a>
        <a href="{% url "portfolio:achievements_rewards" %}">Achievements and Awards</a>
        <div class="topnav-right">
            <a href="{% url "portfolio:community_service" %}">Community service</a>
            <a href="{% url "portfolio:gallery" %}">Gallery</a>
            <a href="{% url "portfolio:contact" %}">Contact</a>
        </div>
        <a href="" class="icon" onclick="responsiveFunction()">
            <i class="fa fa-bars"></i>
        </a>
    </div>
<div data-role="page" id="{% block page_id %}home{% endblock %}">
    <div data-role="header">
    {% block content %}{% endblock %}
    </div>
    <footer class="bg-dark footer-section">
        <div class="border-top text-center border-dark py-3" style="color: #ddd">
          <div data-role="footer" data-theme="a">
            <h5><center>&copy; {% now 'Y' %} Nyarai Tunjera (Pty) Ltd, all rights reserved</center></h5>
        </div><!-- /footer -->
        </div>
      </footer>
      <!-- /footer -->
</div>
<script>
        function responsiveFunction() {
          var x = document.getElementById("myTopnav");
          if (x.className === "topnav") {
            x.className += " responsive";
          } else {
            x.className = "topnav";
          }
        }
</script>
</body>
</html

portfolio/templates/portfolio/community_service.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="col-md-10 offset-md-1" style="background-color:azure">
  <br>
    <p><h1>Community service</h1></p>
    <hr>
    <br>
    <p>Nyarai is passionate about empowering women in technology fields. Her short term goal is to establish an IT academy that targets women. Being a one-time mentor in Techwomen, she envisions that empowered women will improve communities.</p>
    <br>
    <p>Currently is part of church virtual communities that encourages women and girls to up skill themselves in their areas of passion and advice on current scarce skills. #Rise and Shine girl; #FIF Technocrats</p>
    <ol>
      <li>Academic Researchers’ Forum - <a href="https://www.facebook.com/academicResearchersForum/">https://www.facebook.com/academicResearchersForum/</a></li>
      <li>Techwomen mentor <a href="https://www.techwomen.org">https://www.techwomen.org</a></li>
      <li>2012 – 2014 - National coordinator ENO-Zimbabwe <a href="https://www.enoprogramme.org">https://www.enoprogramme.org</a></li>
      <li>2001 – 2007 Mtando-Africa – Online mentoring web design coaching, graphic designing</li>
      <br>
      <br>
    </ol>
</div>
<br>
<br>
{% endblock %}

portfolio/templates/portfolio/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="col-md-10 offset-md-1" style="background-color:azure">
    <br>
    <p><h1>Contact</h1></p>
    <hr>
    <br>
    <div>
        <p><h3>Cape Peninsula University of Technology</h3></p>
        <p>Mowbray</p>
        <p>Cape Town</p>
        <p>South Africa</p>
        <br>
        <p><h2>Social media widgets for Facebook, Twitter, LinkedIn, blog</h2></p>
        <p><img src="/static/img/IconLinkedIn.png" width="40" style="padding-top:1px; padding-right:10px"/><a href="https://www.linkedin.com/in/dr-nyarai-tunjera-96094138/">Linkedin</a></p>
        <p><img src="/static/img/Icon-Facebook.png" width="40" style="padding-top:1px; padding-right:10px"/><a href="https://www.facebook.com/ntunjera">Facebook</a></p>
        <p><img src="/static/img/academia-393876.png" width="40" style="padding-top:1px; padding-right:10px"/><a href="http://capepeninsula.academia.edu/NyaraiTunjera">Academia</a></p>
        <p><img src="/static/img/IconTwitter.png" width="40" style="padding-top:1px; padding-right:10px"/><a href="https://twitter.com/ntunjera">Twitter</a></p>
        <br>
        <p><button><a href="{% url "blog:blog_index" %}"">View blog posts</a></button></p>
        <p><button><a href="{% url "blog:new_post" %}"">Add blog posts</a></button></p>
    </div>
</div>
 {% endblock %}

portfolio/templates/portfolio/gallery.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="col-md-10 offset-md-1" style="background-color:azure">
    <br> 
    <p><h1>Gallery</h1></p>
    <hr>
    <br>
    <p><h2><center>Pictures</center></h2></p>
    <div>
        <div style="transform:rotateZ(0deg); width: 600px; height: 1000px;">
            <img src="/static/img/0_20191030_090311.jpg" alt="" width="600" class="myAnim" style="padding-top:100px; padding-left:100px; transform:scale(0.5,0.5, 0.5); animation-name:inherit; animation-duration:inherit; animation-delay:3s; animation-direction: alternate-reverse "/></a>
        </div>
        <br>
        <br>
        <div style="transform:rotateZ(0deg); border-block:inherit">
            <img src="/static/img/0_20191104_144919.jpg" alt="" width="600" style="padding-top:200px; padding-left:100px; animation-name:inherit; animation-duration:inherit; animation-delay:1s; animation-direction: alternate-reverse"/></a>
        </div>
        <br>
        <br>
        <br>
        <br>
        <br>
        <div style="transform:rotateZ(0deg)">
            <img src="/static/img/1586262063269_0_20191030_171208.jpg" alt="" width="600" style="padding-top:50px; padding-left:100px"/></a>
        </div>
        <br>
        <div style="transform:rotateZ(0deg)">
                <img src="/static/img/0_20191029_140238.jpg" alt="" width="600"  style="padding-top:50px;  padding-left:100px"/></a>
        </div>
        <br>
        <br>
        <div>
            <img src="/static/img/0_20191030_110356.jpg" alt="" width="600" style="padding-top:100px;  padding-left:100px"/></a>
        </div>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <div>
            <img src="/static/img/0_20191128_204512.jpg" alt="" width="600" style="padding-top:50px; padding-left:100px"/></a>
        </div>
    </div>
    <br>
    <br>
    <hr style="color:black">
    <hr style="color:black">
    <div>
        <p><h2><center>Videos</center></h2></p>
    </div>
</div>
<br>
<br>
{% endblock %}

portfolio/templates/portfolio/home.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
{% endblock %}
{% block content %}
<div class="col-md-10 offset-md-1" style="background-color:azure">
<br>
    <p><h1>Home</h1></p>
    <hr>
    <br>
    <div>
        <div>
            <p>Nyarai Tunjera is a researcher and educator in educational technology and IT. Currently she is postdoc fellow at CPUT, in a project 21st century education. Nyarai believes that education and technology should be inclusive and accessible for all. As growing technology researcher, her research focuses on technology-enhanced education in teacher preparation and higher education.</p>
        </div>
        <h4>Profile and expertise</h4>
        <div>
            <p>Dr Nyarai Tunjera is passionate about research on technology in education, specifically with regards to teacher preparation and higher education. In 2010, Nyarai joined higher education as a teaching assistant at Bindura University of Science Education as a Computer Science educator. During this period she awarded research grant in a community project. In July 2012, she was awarded a Mellon scholarship to study a post graduate diploma in education and Master in ICTs in Education programme at UCT being supervised by Prof Dick Ng’ambi and graduated December 2014.</p>
        </div>
        <div>
            <p>In 2015, Nyarai enrolled for doctorate degree at CPUT under the mentorship of NRF C1-rated, Professor Agnes Chigona. Nyarai sees her doctoral study as her current greatest academic success, mainly because it has educational imperatives linked to it. Dr Nyarai derived a model she coined ConTIS model as the innovation from her research. The model guides technology integration instructional strategies that should be followed by teacher training institutions to prepare teacher well enough for technology integrated classroom environment.</p>
        </div>
        <div>
            <p>Currently, Nyarai is enrolled as a postdoc fellow in a 21st century education NRF funded project. Mentor and mentee are currently engaged in writing a Technology integration book.</p>
        </div>
        <br>
        <h4>Research and research goals</h4>
        <div>
            <p>The 21st century requires that students acquire communication, collaboration, critical thinking and creativity. These skills can be easily acquired the use of digital technology-enhanced practices at higher education institutions. Imparting such skills is only possible when higher education educators are equipped in technology integration into their practices.</p>
        </div>
    </div>
    <br>
    <br>
</div>
{% endblock %}

portfolio/templates/portfolio/index.html
{% extends 'base.html' %}
{{% load static %}
{% block header %}
{% endblock %}
{% block content %}
<div class="col-md-10 offset-md-1" style="background-color:azure">
  <br>
  <h4><center>Welcome to Nyarai Tunjera's Website</center></h4>
</div>
{% endblock %}